spring.application.name=security-api

spring.datasource.url=jdbc:postgresql://localhost:5432/security_db
spring.datasource.username=security_user
spring.datasource.password=security_pwd

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=admin@security.com

app.jwt.issuer=com.jdc.security.demo
app.jwt.access-life=1
app.jwt.refresh-life=3

