create table PRODUCT (
	code varchar(40) not null,
	name varchar(40) not null,
	price integer not null,
	primary key (code)
);

create table SALE_HISTORY (
	id integer GENERATED BY DEFAULT AS IDENTITY,
	sale_person varchar(40) not null,
	sale_at timestamp null default CURRENT_TIMESTAMP,
	primary key (id)
);

create table SALE_PRODUCT (
	code varchar(40) not null,
	sale_id integer not null,
	unit_price integer not null,
	quantity integer not null,
	primary key (code, sale_id),
	foreign key (code) references PRODUCT (code),
	foreign key (sale_id) references SALE_HISTORY (id)
);