services:
  db:
    image: postgres:17.6-alpine
    container_name: courses-db
    environment:
      - POSTGRES_DB=coursesdb
    env_file:
      - .env.postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dbdata: