import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Type of Fetches",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <header className="px-16 py-4 bg-teal-500">
          <nav className="flex justify-between">
            <Link className="text-xl font-semibold" href={"/"}>Featch Types</Link>

            <div className="space-x-6">
              <Link href={"/ssc"}>Server Side</Link>
              <Link href={"/csc"}>Client Side</Link>
              <Link href={"/csa"}>Server Action</Link>
            </div>
          </nav>
        </header>

        <main className="px-16 py-4">
          {children}
        </main>
      </body>
    </html>
  );
}
